### ISSUE TITLE
Golding Mining Quest Contract not current

### ISSUE THREAD

**Issue by NichJohn83** [0rtis/dfktools#28]
When attempting to send heroes on the gold mining quest with the following code:

`questV2.start_quest(quest_contract, group, attempts, level, private_key, w3.eth.getTransactionCount(account_address), gas_price_gwei, tx_timeout)`

The following error occurs:

`execution reverted: quest not active`

**Comment by SiddhantKapil** [comment]
You have to use quest_v1 for mining

**Comment by NichJohn83** [comment]
perfect. got it working. thank you @SiddhantKapil
