### ISSUE TITLE
Issue with bid_hero

### ISSUE THREAD

**Issue by big-analytics** [0rtis/dfktools#31]
I am trying to use the auction modules, but when trying to call bid_hero I get this error.

![image](https://user-images.githubusercontent.com/6090054/174903357-7b1966c7-302f-4ad3-b808-76239e741d63.png)

**Comment by big-analytics** [comment]
I found it, converted my input into token_id into an integer before. 

But now, next to the following one.

![image](https://user-images.githubusercontent.com/6090054/175119374-25ceb3fd-a512-4e86-8e84-c91cd3953bcb.png)

I am pushing 'nonce' as input.

**Comment by 0rtis** [comment]
It has been a while so I hope you figured it out.
If not, it looks like you are passing a passing a string "nonce" for the parameter _nonce_ while a int is expected (use `w3.eth.account.privateKeyToAccount(private_key).address` to get the current nonce)
