### ISSUE TITLE
Add questV2 reward keys

### ISSUE THREAD

**Issue by YourAverageLord** [0rtis/dfktools#36]
https://github.com/0rtis/dfktools/blob/55e2a4b7efafa210be351661e0468696ec1177f9/src/dfktools/quests/utils/utils.py#L74

Line 74 and 75 the dict keys for quest V2 are different.
        item = rew['args']['rewardItem']   # V2 = rew['args']['reward']
        qty = rew['args']['itemQuantity']   # V2 = rew['args']['amount']

Everything else is the same

**Comment by 0rtis** [comment]
Fixed in [c231d3e](https://github.com/0rtis/dfktools/commit/c231d3eafe965cb12d2b79a6d5693d2a17bf8f46)
