### ISSUE TITLE
How to retrieve latest hero purchases?

### ISSUE THREAD

**Issue by GuidoBartoli** [0rtis/dfktools#41]
Hi, in the spirit of [DFK Heroes Price Prediction](https://dfk-heroes.herokuapp.com/), I would like to retrieve the last N purchases of heroes together with their paid price. From them, I already know how to query for IDs and get all the hero stats ("hero_example.py"), but I do not know how to do the first step.

Is this possible with "dfktools"?

Many thanks

**Comment by Athiriyya** [comment]
You'll probably get better answers to dev-related questions at the [DFK Dev Discord](https://discord.gg/eQuB3stu).  For your particular question, take a look at the [auction example](https://github.com/0rtis/dfktools/blob/master/src/dfktools/auction_example.py), or check out the GraphQL v6 Auctions API, such as [this example](https://defi-kingdoms-community-api-gateway-co06z8vi.uc.gateway.dev/graphql?query=%7B%0A%09saleAuctions%20(%0A%20%20%20%20first%3A%2010%0A%20%20%20%20skip%3A%200%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20%20%20open%3A%20true%2C%20%0A%20%20%20%20%7D%0A)%7B%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20id%0A%20%20%20%20open%0A%20%20%20%20seller%7B%20id%7D%0A%20%20%20%20startingPrice%0A%20%20%20%20endingPrice%0A%20%20%20%20purchasePrice%0A%20%20%20%20duration%0A%20%20%20%20startedAt%0A%20%20%20%20endedAt%0A%20%20%20%20tokenId%20%7B%20%20%20%20id%20mainClass%7D%0A%20%20%20%20winner%20%7B%20name%7D%0A%20%20%7D%0A%7D). Good luck and come see us on the Discord!

**Comment by 0rtis** [comment]
What @Athiriyya said

**Comment by GuidoBartoli** [comment]
Ok, thanks, I will look into that!
