### ISSUE TITLE
Unable to call functions with Crystalvale's JEWEL address. ERROR: InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

### ISSUE THREAD

**Issue by timtan-github** [0rtis/dfktools#56]
Attempting to use CV's JEWEL address in any functions that uses "token_address" as the variable causes the error "InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes". 

`import dfktools.dex.erc20 as tokens
import logging
import sys
from web3 import Web3
log_format = '%(asctime)s|%(name)s|%(levelname)s: %(message)s'

logger = logging.getLogger("DFK-erc20")
logger.setLevel(logging.DEBUG)
logging.basicConfig(level=logging.INFO, format=log_format, stream=sys.stdout)

rpc_server = 'https://subnets.avax.network/defi-kingdoms/dfk-chain/rpc'
logger.info("Using RPC server " + rpc_server)

w3 = Web3(Web3.HTTPProvider(rpc_server))

realm = 'crystalvale'
crystalvale_items = tokens.get_realm_item_list(realm)
logger.info('{} items in {}'.format(len(serendale_items), realm))
token_address = tokens.symbol2address('JEWEL', realm)
name = tokens.name(token_address, rpc_server)
`

^Errors out at "tokens.name(token_address, rpc_server)" or any other functions that uses CV JEWEL's token address. Functions work for other token addresses that is not CV JEWEL. i.e. CV Crystal address works fine.

Any ideas?

**Comment by timtan-github** [comment]
Found that it's likely the contract address for CV Jewel isn't "0x4f60a160D8C2DDdaAfe16FCC57566dB84D674BD6" as per "get_realm_item_list". Looking at dfk-chain explorer, CV jewel is supposedly "Wrapped JEWEL - 0xCCb93dABD71c8Dad03Fc4CE5559dC3D89F67a260" but if you call balanceOf function with Wrapped JEWEL address on a wallet, it seems to return 0. Very strange...

**Comment by etjones** [comment]
Couple things:  Jewel isn’t an ERC20 token on DFK Chain, it’s the gas token.  Mostly you need to treat it like ‘ether’.  So you can’t query for balance or transfer it on DFK Chain like you would Crystal or Bloaters or whatever. I’ll see if I can post some examples later on. 

Second, your code looks like it’s using the Harmony RPC; you’ll need to use a DFK Chain RPC instead. That should be in the docs, too.

**Comment by timtan-github** [comment]
Ahh noted on the gas token part. I'm still very new to web3 dev work. Thanks for clarifying. 

Nah, I'm using DFK Chain RPC. I swapped it out in my scripts. I've also had to change the UniswapV2Factory.py contract to reflect the DFK Chain's address to get my scripts to run. Otherwise it would be throwing errors. Basically, the current UniswapV2Factory.py script is pointing to the C-Chain address.

**Comment by Athiriyya** [comment]
So, to get Jewel inventory on DFK Chain, you'll want to do:
```python
rpc_server = 'https://subnets.avax.network/defi-kingdoms/dfk-chain/rpc'
w3 = Web3(Web3.HTTPProvider(rpc_server))
amount_wei = w3.eth.get_balance(account_address)
amount = w3.fromWei(amount_wei, 'ether')
```

This is because Jewel is the 'Ethereum' of the DFK Chain. There is also `wJEWEL`, which IS an ERC20 token. That's what gets awarded in gardening quests, for example. By some magic I don't totally understand, that wrapped Jewel gets turned into normal Jewel.

**Comment by timtan-github** [comment]
Hey Athiriyya, yup that works! I'm still figuring out how to work with gas tokens properly for swaps. Thanks!
